### ISSUE TITLE
Add features to existing practice session page

### ISSUE THREAD

**Issue by milindvishnoi** [grey-software/Material-Math#11]
# Overview
Displays one questions at a time with the specified features below:

- [x]  Timer or Progress Bar #7
- [x] Skip Button #8
- [x] Current Streak Count #9
- [x] Animated Feedback for Correct/Incorrect Answers #10
